from characters import Character
characters = [
    Character(id=1, name="Alex", glasses=False, skin_tone='medium', hair_color='brown', eye_color='brown', sex='male', facial_hair='none', hat=False, image='characters_images/alex.png'),
    Character(id=2, name="Alfred", glasses=False, skin_tone='medium', hair_color='white', eye_color='blue', sex='male', facial_hair='moustache', hat=False, image='characters_images/alfred.png'),
    Character(id=3, name="Anita", glasses=False, skin_tone='light', hair_color='blonde', eye_color='blue', sex='female', facial_hair='none', hat=False, image='characters_images/anita.png'),
    Character(id=4, name="Anne", glasses=False, skin_tone='light', hair_color='red', eye_color='green', sex='female', facial_hair='none', hat=False, image='characters_images/anne.png'),
    Character(id=5, name="Bernard", glasses=True, skin_tone='medium', hair_color='brown', eye_color='brown', sex='male', facial_hair='none', hat=False, image='characters_images/bernard.png'),
    Character(id=6, name="Bill", glasses=False, skin_tone='light', hair_color='red', eye_color='blue', sex='male', facial_hair='beard', hat=False, image='characters_images/bill.png'),
    Character(id=7, name="Charles", glasses=False, skin_tone='light', hair_color='black', eye_color='brown', sex='male', facial_hair='moustache', hat=False, image='characters_images/charles.png'),
    Character(id=8, name="Claire", glasses=False, skin_tone='light', hair_color='black', eye_color='blue', sex='female', facial_hair='none', hat=True, image='characters_images/claire.png'),
    Character(id=9, name="David", glasses=False, skin_tone='light', hair_color='blonde', eye_color='brown', sex='male', facial_hair='none', hat=False, image='characters_images/david.png'),
    Character(id=10, name="Eric", glasses=True, skin_tone='medium', hair_color='white', eye_color='brown', sex='male', facial_hair='none', hat=False, image='characters_images/eric.png'),
    Character(id=11, name="Frans", glasses=False, skin_tone='light', hair_color='brown', eye_color='blue', sex='male', facial_hair='none', hat=False, image='characters_images/frans.png'),
    Character(id=12, name="George", glasses=False, skin_tone='light', hair_color='white', eye_color='brown', sex='male', facial_hair='none', hat=True, image='characters_images/george.png'),
    Character(id=13, name="Herman", glasses=False, skin_tone='light', hair_color='blonde', eye_color='blue', sex='male', facial_hair='moustache', hat=False, image='characters_images/herman.png'),
    Character(id=14, name="Joe", glasses=False, skin_tone='dark', hair_color='black', eye_color='brown', sex='male', facial_hair='none', hat=False, image='characters_images/joe.png'),
    Character(id=15, name="Maria", glasses=False, skin_tone='medium', hair_color='brown', eye_color='brown', sex='female', facial_hair='none', hat=False, image='characters_images/maria.png'),
    Character(id=16, name="Max", glasses=False, skin_tone='light', hair_color='blonde', eye_color='blue', sex='male', facial_hair='none', hat=True, image='characters_images/max.png'),
    Character(id=17, name="Paul", glasses=False, skin_tone='light', hair_color='white', eye_color='blue', sex='male', facial_hair='beard', hat=False, image='characters_images/paul.png'),
    Character(id=18, name="Peter", glasses=False, skin_tone='light', hair_color='white', eye_color='blue', sex='male', facial_hair='none', hat=False, image='characters_images/peter.png'),
    Character(id=19, name="Philip", glasses=True, skin_tone='medium', hair_color='brown', eye_color='brown', sex='male', facial_hair='none', hat=False, image='characters_images/philip.png'),
    Character(id=20, name="Richard", glasses=False, skin_tone='medium', hair_color='black', eye_color='brown', sex='male', facial_hair='none', hat=True, image='characters_images/richard.png'),
    Character(id=21, name="Robert", glasses=False, skin_tone='light', hair_color='brown', eye_color='blue', sex='male', facial_hair='beard', hat=False, image='characters_images/robert.png'),
    Character(id=22, name="Sam", glasses=True, skin_tone='medium', hair_color='white', eye_color='brown', sex='male', facial_hair='none', hat=False, image='characters_images/sam.png'),
    Character(id=23, name="Susan", glasses=False, skin_tone='light', hair_color='red', eye_color='green', sex='female', facial_hair='none', hat=False, image='characters_images/susan.png'),
    Character(id=24, name="Tom", glasses=False, skin_tone='dark', hair_color='black', eye_color='brown', sex='male', facial_hair='none', hat=False, image='characters_images/tom.png'),
]
